#!/bin/bash
function is_int() { return $(test "$@" -eq "$@" > /dev/null 2>&1); }
ssh-add -D
git init
git config --global --unset user.name
git config --global --unset user.email
git config user.name "2634367"
git config user.email "cerbus.2@wright.edu"
ssh-add -k /Users/morpheous/.ssh/github-wright-edu
LastCommit=$(git rev-list HEAD --count)
if $(is_int "${LastCommit}"); then
	NextCommitNumber=$((LastCommit+1))
else
	echo "Not an integer Resetting"
	NextCommitNumber=1
fi
git add .
git commit -m "$NextCommitNumber"
git remote add origin git@github.com:2634367/neuro-4210.git || echo ""
git push origin master
